# Generated by Django 3.1.2 on 2020-11-16 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jade_island_post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments_xtd', '0008_auto_20200920_2037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomComment',
            fields=[
                ('xtdcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments_xtd.xtdcomment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('submit_date',),
                'permissions': [('can_moderate', 'Can moderate comments')],
                'abstract': False,
            },
            bases=('django_comments_xtd.xtdcomment',),
        ),
        migrations.CreateModel(
            name='JadeIslandPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=5000, null=True)),
                ('post_category', models.CharField(choices=[('E', 'Event'), ('P', 'Place'), ('T', 'Tip'), ('SM', 'Shared Moment'), ('S', 'Sale'), ('J', 'Job'), ('AD', 'Advert'), ('UN', 'UN Categorized')], default='UN', max_length=5)),
                ('location', models.TextField(max_length=255, null=True)),
                ('contact', models.TextField(max_length=255, null=True)),
                ('job_start_date', models.DateTimeField(blank=True, null=True)),
                ('sale_item_price_rmb', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('event_start_date', models.DateTimeField(blank=True, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('url_field', models.URLField(blank=True, max_length=255, null=True)),
                ('event_category', models.CharField(choices=[('ED', 'Educational or Inspirational'), ('EN', 'Entertainment'), ('EX', 'Exhibition or Trade fair'), ('CH', 'Charity or Fund Raising'), ('AC', 'Awards and Competitions'), ('CO', 'Conference or Meeting'), ('NS', 'Networking Sessions'), ('O', 'Other'), ('W', 'WEBINARS')], default='O', max_length=5, null=True)),
                ('place_category', models.CharField(choices=[('D', 'Dining'), ('P', 'Playing'), ('L', 'Learning'), ('H', 'Health'), ('LO', 'Locals'), ('S', 'Staying'), ('O', 'Other')], default='O', max_length=5, null=True)),
                ('sale_category', models.CharField(choices=[('AC', 'Arts & Crafts'), ('BC', 'Baby & Children'), ('CA', 'Clothing & Apparel'), ('EI', 'Electronics'), ('HS', 'Health & Sports'), ('HF', 'Home & Furniture'), ('PA', 'Pets & Animals'), ('SE', 'Services'), ('V', 'Vehicles'), ('O', 'Other')], default='O', max_length=5, null=True)),
                ('job_category', models.CharField(choices=[('ET', 'Teaching English'), ('NET', 'Teaching Other Subjects'), ('NT', 'Non Teaching')], default='ET', max_length=5, null=True)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('FR', 'Contract or Freelance'), ('INT', 'Paid Internship'), ('VT', 'Volunteer or Unpaid Internship')], default='FT', max_length=5, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_one', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_two', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_three', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_four', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_five', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_six', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_seven', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_eight', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('extra_image_nine', models.ImageField(blank=True, null=True, upload_to=jade_island_post.models.upload_location)),
                ('tags', models.TextField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='jade_island_post_post_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='jade_island_post_post_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
