# Generated by Django 3.1.2 on 2020-11-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jade_island_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadeislandpost',
            name='body',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='contact',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='event_category',
            field=models.CharField(blank=True, choices=[('ED', 'Educational or Inspirational'), ('EN', 'Entertainment'), ('EX', 'Exhibition or Trade fair'), ('CH', 'Charity or Fund Raising'), ('AC', 'Awards and Competitions'), ('CO', 'Conference or Meeting'), ('NS', 'Networking Sessions'), ('O', 'Other'), ('W', 'WEBINARS')], default='O', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='job_category',
            field=models.CharField(blank=True, choices=[('ET', 'Teaching English'), ('NET', 'Teaching Other Subjects'), ('NT', 'Non Teaching')], default='NT', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('FR', 'Contract or Freelance'), ('INT', 'Paid Internship'), ('VT', 'Volunteer or Unpaid Internship')], default='FT', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='location',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='place_category',
            field=models.CharField(blank=True, choices=[('D', 'Dining'), ('P', 'Playing'), ('L', 'Learning'), ('H', 'Health'), ('LO', 'Locals'), ('S', 'Staying'), ('O', 'Other')], default='O', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='sale_category',
            field=models.CharField(blank=True, choices=[('AC', 'Arts & Crafts'), ('BC', 'Baby & Children'), ('CA', 'Clothing & Apparel'), ('EI', 'Electronics'), ('HS', 'Health & Sports'), ('HF', 'Home & Furniture'), ('PA', 'Pets & Animals'), ('SE', 'Services'), ('V', 'Vehicles'), ('O', 'Other')], default='O', max_length=5, null=True),
        ),
    ]
