# Generated by Django 3.1.2 on 2020-11-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jade_island_post', '0002_auto_20201116_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadeislandpost',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='job_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
