# Generated by Django 3.1.2 on 2020-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jade_island_post', '0003_auto_20201116_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadeislandpost',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jadeislandpost',
            name='job_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
